security:
  paths: /auth/**, /error/**, /security/health/**, /actuator/**, api/sales/**, api/persons/**, api/ai/**, /v3/api-docs/**, /swagger-ui/**, /swagger-ui.html
jwt:
  expiration: ${JWT_EXPIRATION:86400000}
  secret: ${JWT_SECRET:three-db-in-one-modulesi13112023secretkey123456789012}
